project_id = "juchtmjczkgodlsdrjvq"

[functions.send-invoice-email]
verify_jwt = false

[functions.check-expired-payments]
verify_jwt = false

[functions.midtrans-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false